### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by luisivan** [atvanguard/ethindia-arquest#1]
Hey there! Very cool project and congrats for the ETHIndia prize!

I was running it locally and wondered if it needs some sort of Finance app or ETH in the DAO for it to work. I know this was done in a hackathon so I guess there was no time for documentation, but I'd love to see a quick *how to use ArQuest* guide in the readme.

**Comment by arminvoid** [comment]
Hey @luisivan 
Thank you and It's an honour hearing from you!
The project needs quite a setup to run end-to-end (`aragon run`, request network, event listeners etc.) and there are a lot of parts that are hanging by a thread. I'll need to make changes to make it work. For now you can view the project demo here: https://youtu.be/E0p5Bjhkb30

That said, I have already submitted this project idea to another 2-month hackathon, where I plan to make it into a production ready app. See [proposal](https://github.com/Blockternship/projects/issues/11). @izqui has been assigned to mentor us for the same. I would appreciate your inputs on the idea and what you think about the demo :)

Thank you.

**Comment by luisivan** [comment]
Awesome! Nice to hear. Looking forward to seeing your progress during the next couple of months! I'll close this issue for now, you'll be in good hands with @izqui :)
